# Generated by Django 3.1.5 on 2021-04-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shellacmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='audiolabel',
            field=models.CharField(default='', max_length=360),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marker',
            name='audio',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='marker',
            name='flag',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='marker',
            name='heading',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='marker',
            name='text',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='marker',
            name='video',
            field=models.CharField(max_length=360),
        ),
    ]
